import { useState } from "react";
import { useParams, useNavigate } from "react-router";
import { motion } from "framer-motion";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import {
  TrendingUp,
  Shield,
  DollarSign,
  Users,
  MessageSquare,
  ArrowLeft,
} from "lucide-react";
import { cn } from "@/lib/utils";

const PILLAR_CONFIG = {
  marketClarity: {
    label: "Market Clarity",
    icon: TrendingUp,
    color: "text-chart-1",
    description: "Market definition, TAM/SAM credibility, competitor awareness",
  },
  techDefensibility: {
    label: "Tech Defensibility",
    icon: Shield,
    color: "text-chart-2",
    description: "IP strength, technical moat, differentiation",
  },
  unitEconomicLogic: {
    label: "Unit Economic Logic",
    icon: DollarSign,
    color: "text-chart-3",
    description: "CAC, LTV, runway, burn rate sustainability",
  },
  investorReadiness: {
    label: "Investor Readiness",
    icon: Users,
    color: "text-chart-5",
    description: "Coachability, defensiveness, pitch quality",
  },
};

export default function ReportCard() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();
  const [selectedPillar, setSelectedPillar] = useState<string | null>(null);

  // TEST MODE: Using no-auth version
  const session = useQuery(
    api.sessions_noauth.getPitchSession,
    sessionId ? { sessionId: sessionId as Id<"pitchSessions"> } : "skip"
  );

  if (!sessionId) {
    navigate("/war-room");
    return null;
  }

  if (!session) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-4">
          <div className="animate-spin w-12 h-12 border-4 border-primary border-t-transparent rounded-full mx-auto" />
          <p className="text-muted-foreground font-mono-terminal">
            Generating your Fundability Report Card...
          </p>
        </div>
      </div>
    );
  }

  if (!session.reportCard) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-4">
          <div className="animate-pulse">
            <div className="text-6xl mb-4">🧠</div>
          </div>
          <p className="text-muted-foreground font-mono-terminal">
            Analyzing your pitch with Llama 3.1 70B...
          </p>
        </div>
      </div>
    );
  }

  const { reportCard } = session;

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-chart-2";
    if (score >= 60) return "text-chart-3";
    return "text-destructive";
  };

  const getScoreGrade = (score: number) => {
    if (score >= 90) return "A";
    if (score >= 80) return "B";
    if (score >= 70) return "C";
    if (score >= 60) return "D";
    return "F";
  };

  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      {/* Grid background */}
      <div className="absolute inset-0 bg-[linear-gradient(rgba(94,106,210,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(94,106,210,0.03)_1px,transparent_1px)] bg-[size:64px_64px]" />

      <div className="relative z-10 container mx-auto px-4 py-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-6xl mx-auto"
        >
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <Button
              variant="ghost"
              onClick={() => navigate("/war-room")}
              className="gap-2"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to War Room
            </Button>
            <div className="text-right">
              <p className="text-sm font-mono-terminal text-muted-foreground">
                SESSION ID
              </p>
              <p className="text-xs font-mono-terminal">{sessionId}</p>
            </div>
          </div>

          {/* Overall Score */}
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="glass-card p-12 mb-8 text-center"
          >
            <h1 className="text-4xl font-bold font-mono-terminal mb-2">
              FUNDABILITY REPORT CARD
            </h1>
            <p className="text-muted-foreground mb-8">
              Generated by OpenAI o1-mini using the Bill Payne Scorecard Method
            </p>

            <div className="flex items-center justify-center gap-8">
              <div>
                <div
                  className={cn(
                    "text-8xl font-bold font-mono-terminal",
                    getScoreColor(reportCard.overallScore)
                  )}
                >
                  {Math.round(reportCard.overallScore)}
                </div>
                <p className="text-sm text-muted-foreground mt-2">
                  OVERALL SCORE
                </p>
              </div>

              <div className="text-left">
                <div
                  className={cn(
                    "text-6xl font-bold font-mono-terminal",
                    getScoreColor(reportCard.overallScore)
                  )}
                >
                  {getScoreGrade(reportCard.overallScore)}
                </div>
                <p className="text-sm text-muted-foreground mt-2">GRADE</p>
              </div>
            </div>

            {reportCard.coachabilityDelta !== 0 && (
              <div
                className={cn(
                  "mt-6 inline-flex items-center gap-2 px-4 py-2 rounded-full border font-mono-terminal",
                  reportCard.coachabilityDelta > 0
                    ? "border-chart-2 text-chart-2 bg-chart-2/10"
                    : "border-destructive text-destructive bg-destructive/10"
                )}
              >
                <span className="text-xs">COACHABILITY DELTA:</span>
                <span className="text-lg font-bold">
                  {reportCard.coachabilityDelta > 0 ? "+" : ""}
                  {reportCard.coachabilityDelta}
                </span>
              </div>
            )}
          </motion.div>

          {/* Four Pillars */}
          <div className="grid md:grid-cols-2 gap-6 mb-8">
            {Object.entries(PILLAR_CONFIG).map(([key, config], index) => {
              const score = reportCard[key as keyof typeof reportCard] as number;
              const Icon = config.icon;

              return (
                <motion.div
                  key={key}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.3 + index * 0.1 }}
                >
                  <Card
                    className={cn(
                      "glass-card p-6 cursor-pointer transition-all hover:border-primary",
                      selectedPillar === key && "border-primary glow-electric"
                    )}
                    onClick={() =>
                      navigate(`/mentorship/${sessionId}?focus=${key}`)
                    }
                  >
                    <div className="flex items-start justify-between mb-4">
                      <div className="flex items-center gap-3">
                        <div
                          className={cn(
                            "p-2 rounded-lg bg-primary/10",
                            config.color
                          )}
                        >
                          <Icon className="w-5 h-5" />
                        </div>
                        <div>
                          <h3 className="font-semibold">{config.label}</h3>
                          <p className="text-xs text-muted-foreground">
                            {config.description}
                          </p>
                        </div>
                      </div>

                      <div
                        className={cn(
                          "text-3xl font-bold font-mono-terminal",
                          getScoreColor(score)
                        )}
                      >
                        {Math.round(score)}
                      </div>
                    </div>

                    <Progress value={score} className="mb-2" />

                    <div className="flex items-center justify-between text-xs">
                      <span
                        className={cn(
                          "font-mono-terminal font-bold",
                          getScoreColor(score)
                        )}
                      >
                        {getScoreGrade(score)} GRADE
                      </span>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="gap-1 h-auto py-1 px-2"
                      >
                        <MessageSquare className="w-3 h-3" />
                        <span className="text-xs">Improve This</span>
                      </Button>
                    </div>
                  </Card>
                </motion.div>
              );
            })}
          </div>

          {/* Insights */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7 }}
          >
            <Card className="glass-card p-8">
              <h3 className="text-xl font-semibold font-mono-terminal mb-4">
                BRUTAL ASSESSMENT
              </h3>
              <p className="text-foreground/90 leading-relaxed">
                {reportCard.insights}
              </p>

              <div className="mt-8 pt-8 border-t border-border">
                <Button
                  onClick={() => navigate(`/mentorship/${sessionId}`)}
                  className="w-full glow-electric"
                  size="lg"
                >
                  <MessageSquare className="mr-2" />
                  Enter Socratic Mentorship Mode
                </Button>
              </div>
            </Card>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
}
